spring:
  application:
    name: issuetracker

  jpa:
    open-in-view: false

  data:
    web:
      pageable:
        max-page-size: 100

jwt:
  secret: ${JWT_SECRET}

springdoc:
  default-produces-media-type: application/json
  override-with-generic-response: false
